name: zapizza
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  lottie: ^2.6.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.4
  http: ^1.1.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  glass: ^1.0.2+1
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  country_picker: ^2.0.21
  flutter_otp_text_field: ^1.1.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  pinput: ^4.0.0
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  iconsax: ^0.0.8
  fl_country_code_picker: ^0.1.9+1
  otp_timer_button: ^1.1.1
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  eva_icons_flutter: ^3.1.0
  razorpay_flutter: ^1.3.6
  page_transition: ^2.1.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
